import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage => {
  if (value === 'en') return 'en';
  if (value === 'zh_TW' || value === 'zh-TW' || value === 'zh_Hant' || value === 'zh-Hant' || value === 'tw') return 'zh_TW';
  if (value === 'zh') return 'zh';
  return 'zh_TW';
};

const REPORT_TEXT = {
  zh: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暂无分析结论',
    actionAdvice: '操作建议',
    noAdvice: '暂无建议',
    trendPrediction: '趋势预测',
    noPrediction: '暂无预测',
    marketSentiment: '市场情绪',
    strategyPoints: '策略点位',
    sniperLevels: '狙击点位',
    idealBuy: '理想买入',
    secondaryBuy: '二次买入',
    stopLoss: '止损价位',
    takeProfit: '止盈目标',
    noValue: '—',
    newsFeed: '资讯动态',
    relatedNews: '相关资讯',
    refresh: '刷新',
    retry: '重试',
    dismiss: '关闭',
    details: '查看详情',
    loadingNews: '加载资讯中...',
    noNews: '暂无相关资讯',
    noNewsDescription: '可稍后刷新以获取最新资讯。',
    openLink: '跳转',
    transparency: '透明度',
    traceability: '数据追溯',
    rawResult: '原始分析结果',
    analysisSnapshot: '分析快照',
    copy: '复制',
    copied: '已复制',
    recordId: '记录 ID',
    fullReport: '完整分析报告',
    loadingReport: '加载报告中...',
    loadReportFailed: '加载报告失败',
    copyMarkdownSource: '复制 Markdown 源码',
    copyPlainText: '复制纯文本',
    analysisModel: '分析模型',
    fearGreedIndex: '恐惧贪婪指数',
    boardLinkage: '板块联动',
    relatedBoards: '关联板块',
    leadingBoard: '领涨',
    laggingBoard: '领跌',
    neutralBoard: '中性',
    reanalyze: '重新分析',
  },
  zh_TW: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暫無分析結論',
    actionAdvice: '操作建議',
    noAdvice: '暫無建議',
    trendPrediction: '趨勢預測',
    noPrediction: '暫無預測',
    marketSentiment: '市場情緒',
    strategyPoints: '策略點位',
    sniperLevels: '狙擊點位',
    idealBuy: '理想買進',
    secondaryBuy: '二次買進',
    stopLoss: '停損價位',
    takeProfit: '停利目標',
    noValue: '—',
    newsFeed: '資訊動態',
    relatedNews: '相關資訊',
    refresh: '重新整理',
    retry: '重試',
    dismiss: '關閉',
    details: '查看詳情',
    loadingNews: '載入資訊中...',
    noNews: '暫無相關資訊',
    noNewsDescription: '可稍後重新整理以取得最新資訊。',
    openLink: '開啟連結',
    transparency: '透明度',
    traceability: '資料追溯',
    rawResult: '原始分析結果',
    analysisSnapshot: '分析快照',
    copy: '複製',
    copied: '已複製',
    recordId: '記錄 ID',
    fullReport: '完整分析報告',
    loadingReport: '載入報告中...',
    loadReportFailed: '載入報告失敗',
    copyMarkdownSource: '複製 Markdown 原始碼',
    copyPlainText: '複製純文字',
    analysisModel: '分析模型',
    fearGreedIndex: '恐慌貪婪指數',
    boardLinkage: '板塊聯動',
    relatedBoards: '關聯板塊',
    leadingBoard: '領漲',
    laggingBoard: '領跌',
    neutralBoard: '中性',
    reanalyze: '重新分析',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
    reanalyze: 'Reanalyze',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
